### ISSUE TITLE
Basic pip question

### ISSUE THREAD

**Issue by venuv** [kjappelbaum/gpt3forchem#29]
@kjappelbaum  

pip install fails for me (as tried below). I also don't see the library on pypi.org. what should i be doing differently?

----
!pip install git+https://github.com/GPflow/GPflow.git@develop
!pip install gpt3forchem

**Comment by kjappelbaum** [comment]
Hi, thanks for your interest!

Please use https://github.com/kjappelbaum/gptchem, this repository is deprecated, and I'll archive it. 

All the best,
Kevin
